version: '3.9'

services:
  db:
    image: postgres:17

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "5432:5432"

    restart: always
    shm_size: 128mb

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - backend/app/.env

    environment:
      - UVICORN_RELOAD=true

    depends_on:
      - db

